"""
Mapping from raw, inconsistent Common Voice 17 "accent" labels to a small set
of consistent accent classes for the WavLM accent-classification script.

- Labels that describe the same accent in different words (e.g. compound labels
  like "United States English,Midwestern" or aliases like "British accent") are
  collapsed onto one canonical label (e.g. "United States English", "England English").
- Labels that are one-off personal descriptions, ambiguous multi-accent combos with
  no clear primary accent, or accents with too few usable samples (no/almost no
  representation in the validation/test splits) are mapped to "" so that
  `filter_labeled()` in wavlm_common.py drops them automatically (it already treats
  "" the same as an unlabeled example).

Resulting classes and their (train, val, test) sample counts after merging:
    Australian English        1108   27   35
    Canadian English          1566   51   38
    England English           3728  146  150
    Filipino                   209   15    7
    Hong Kong English          197   21   14
    India and South Asia      3105  239  285
    Irish English              315   20   14
    Malaysian English          166    9    9
    New Zealand English        258    8   10
    Scottish English           252    6   14
    Singaporean English        126    9    8
    Southern African           450   26   16
    United States English    12945  603  590
    Welsh English              111    8    7
    West Indies and Bermuda     53    6    6
(365 / 18 / 4 samples in train/val/test were dropped as too rare or unusable.)
"""

ACCENT_LABEL_MAP = {
    '2nd Language ': '',
    'A variety of Texan English with some German influence that has undergone the cot-caught merger': '',
    "A'lo": '',
    'Academic southern English,England English': '',
    'Afrikaans English': '',
    'Australian English': 'Australian English',
    'Australian English,Canadian English': 'Australian English',
    'Australian English,Educated Australian Accent': 'Australian English',
    'Australian English,England English': 'Australian English',
    'Australian English,England English,Japanese': 'Australian English',
    'Australian English,General Australian': 'Australian English',
    'Australian English,Sydney - middle eastern seaboard Australian': 'Australian English',
    'Austrian': '',
    'Bangladeshi English': '',
    'Bangladeshi,Bangladesh English': '',
    'Born in West Germany in 1966, lived in Toronto, Ontario from 1985 to 2004, now in Central America.': '',
    'Brazilian': '',
    'Brazillian Accent': '',
    'British English / Received Pronunciation (RP)': 'England English',
    'British accent': 'England English',
    'Bulgarian': '',
    'California': '',
    'Canadian English': 'Canadian English',
    'Canadian English,Irish English': 'Canadian English',
    'Canadian English,Ontario': 'Canadian English',
    'Canadian English,SerpentX': 'Canadian English',
    'Canadian English,Swedish English': 'Canadian English',
    'Canadian English,United States English': 'Canadian English',
    'Canadian English,United States English,England English': 'Canadian English',
    'Caribbean Canadian ': 'Canadian English',
    'Chinese': '',
    'Czech accent': '',
    'Dutch': '',
    'Dutch English': '',
    'Dutch,European,Adjustable': '',
    'East African Khoja': '',
    'East Indian': '',
    'Eastern European English': '',
    'Eastern European,Romanian': '',
    'England English': 'England English',
    'England English,British': 'England English',
    'England English,Canadian English': 'England English',
    'England English,East Anglian English': 'England English',
    'England English,Educated,non regional': 'England English',
    'England English,India and South Asia (India, Pakistan, Sri Lanka),Nepalese': 'England English',
    'England English,Lancashire, England ': 'England English',
    'England English,New Zealand English': 'England English',
    "England English,Porto des dels 3 anys aprenent anglès a l'escola i actualment m'estic preparant per a l'examen del B2.": 'England English',
    'England English,Received English, tempered by 45 years living in the USA': 'England English',
    'England English,Received Pronunciation': 'England English',
    'England English,Slightly lazy Midlands English ,Oxford English': 'England English',
    'England English,South London': 'England English',
    'England English,South London and Essex': 'England English',
    'England English,Southern England English with a subtle hint of Irish English.': 'England English',
    'England English,Swedish': 'England English',
    'England English,United States English': 'England English',
    'England English,United States English,Brazilian Accent,EFL': 'England English',
    'England English,United States English,English with Polish accent,Slavic English': 'England English',
    'England English,Well spoken softly spoken Home Counties gay,softly spoken male,well spoken male,gay male': 'England English',
    'England English,Welsh English': 'Welsh English',
    'England English,femalepublic school accent, quiet and under articualted finals': 'England English',
    'England English,south German / Swiss accent': 'England English',
    'England English,southern UK,male': 'England English',
    'England English,southern english,sussex': 'England English',
    'England English,yorkshire': 'England English',
    'England West County': 'England English',
    'English north of England ': 'England English',
    'English with Swiss german accent': '',
    'European': '',
    'European English': '',
    'European English,French,Romanian': '',
    'European,German,Foreign,Non-native': '',
    'Filipino': 'Filipino',
    'Filipino,Canadian English': 'Filipino',
    'Filipino,United States English': 'Filipino',
    'French': '',
    'Generic European': '',
    'Georgian English': '',
    'German': '',
    'German Accent': '',
    'German English': '',
    'German English,England English': '',
    'German English,I am German and speak English as learned at school': '',
    'German English,Non native speaker': '',
    'Ghanaian english Accent,african regular reader': '',
    'Greek': '',
    'Hispanic': '',
    'Hong Kong English': 'Hong Kong English',
    'Hong Kong English,Scottish English': 'Hong Kong English',
    'Hungarian': '',
    'Hunglish': '',
    'India and South Asia (India, Pakistan, Sri Lanka)': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Basic': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Canadian English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),England English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),England English,United States English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Indian with a tinge of an RP accent': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),International Indian Accent': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Singaporean English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),United States English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),United States English,England English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),bangladesh': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),try to maintain originality ': 'India and South Asia',
    'Indonesian': '',
    'International English,United States English,Australian English': 'Australian English',
    'Irish English': 'Irish English',
    'Irish English,Northern Irish English,belfast ': 'Irish English',
    'Israeli': '',
    'Israeli English': '',
    'Italian': '',
    'Japanese English': '',
    'Kazakhstan English': '',
    'Kenyan English': '',
    'Kenyan English accent': '',
    'Kiwi': 'New Zealand English',
    'Latin America,United States English': 'United States English',
    'Latin English': '',
    'Latino': '',
    'Latvian': '',
    'Liverpool English,Lancashire English,England English': 'England English',
    'Malaysian English': 'Malaysian English',
    'Malaysian English,England English': 'Malaysian English',
    'Malaysian English,Indonesian English': 'Malaysian English',
    'Malaysian English,Javanese,Indonesian English': 'Malaysian English',
    'Mid-Atlantic United States English,Philadelphia, Pennsylvania, United States English,United States English,Philadelphia Style United States English': 'United States English',
    'Mid-atlantic,England English,United States English': 'United States English',
    'Midatlantic': 'United States English',
    'Midwestern States (Michigan),United States English': 'United States English',
    'Midwestern US English (United States),United States English': 'United States English',
    'Mild Northern England English': 'England English',
    'Mix of american and british accent': '',
    'My accent is influenced by the phones of all letters within a sentence.,Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'Nepali': '',
    'New Zealand English': 'New Zealand English',
    'New Zealand English,Australian English,England English': 'New Zealand English',
    'New Zealand English,England English': 'New Zealand English',
    'New Zealand English,United States English': 'New Zealand English',
    'Nigerian ,West African ': '',
    'Nigerian English': '',
    'Non native speaker from France': '',
    'Non-native': '',
    'Non-native,German Accent': '',
    'North European English': '',
    'Northern England,England English': 'England English',
    'Northern Irish': 'Irish English',
    'Northern Irish,Norwegian,yorkshire': '',
    'Northern Irish,culchie': 'Irish English',
    'Northumbrian British English': 'England English',
    'Personal idiolect': '',
    'Polish English': '',
    'Rhode Island New England Accent': 'United States English',
    'Russian': '',
    'Russian English': '',
    'Russian,East Ukrainian ': '',
    'Scottish English': 'Scottish English',
    'Scottish English,England English': 'Scottish English',
    'Scottish English,Scottish English (West Coast),Scottish English (Ayrshire)': 'Scottish English',
    'Singaporean English': 'Singaporean English',
    'Singaporean English,England English': 'Singaporean English',
    'Singaporean English,Malaysian English': 'Singaporean English',
    'Singaporean English,United States English': 'Singaporean English',
    'Slavic': '',
    'Slavic,East European,polish': '',
    'Slavic,Russian': '',
    'Slavic,polish': '',
    'Slovak': '',
    'South African  English accent ': '',
    'South African English Accent ': '',
    'South African accent ,Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'South Atlantic (Falkland Islands, Saint Helena)': '',
    'South Australia': '',
    'South German accent,Alemannic German Accent,German,south-west German': '',
    'South Indian': '',
    'Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'Southern African (South Africa, Zimbabwe, Namibia),England English': 'Southern African',
    'Southern Californian,United States English': 'United States English',
    'Spanish bilingual': '',
    'Spanish,Foreign,Non-native': '',
    'Swedish English': '',
    'Swedish accent': '',
    'Thai': '',
    'Transatlantic,Danish English': '',
    'Ukrainian': '',
    'United States English': 'United States English',
    'United States English combined with European English': 'United States English',
    'United States English,American Midwest': 'United States English',
    'United States English,American english with austrian accent': 'United States English',
    'United States English,Asian-American English': 'United States English',
    'United States English,Australian English': 'United States English',
    'United States English,Australian English,England English,Irish English': 'United States English',
    'United States English,Australian English,England English,New Zealand English,India and South Asia (India, Pakistan, Sri Lanka),international,Slovak': 'United States English',
    'United States English,British English': 'United States English',
    'United States English,California': 'United States English',
    'United States English,California English': 'United States English',
    'United States English,California English,Southern US English': 'United States English',
    'United States English,California,Valley': 'United States English',
    'United States English,Californian Accent': 'United States English',
    'United States English,Canadian English': 'United States English',
    'United States English,Canadian English,international': 'United States English',
    'United States English,Central American ': 'United States English',
    'United States English,Chicago ': 'United States English',
    'United States English,Cool': 'United States English',
    'United States English,England English': 'United States English',
    'United States English,England English,India and South Asia (India, Pakistan, Sri Lanka)': 'United States English',
    'United States English,English Second Language': 'United States English',
    'United States English,Foreigner English': 'United States English',
    'United States English,German Accent': 'United States English',
    'United States English,Hmong-American': 'United States English',
    'United States English,India and South Asia (India, Pakistan, Sri Lanka)': 'United States English',
    'United States English,Irish English': 'United States English',
    'United States English,Irish English,England English,Scottish English,Danish English': 'United States English',
    'United States English,Like a Kennedy ,Boston': 'United States English',
    'United States English,Mid-atlantic': 'United States English',
    'United States English,Mid-west United States English': 'United States English',
    'United States English,Midwest United States': 'United States English',
    'United States English,Midwestern': 'United States English',
    'United States English,Midwestern USA': 'United States English',
    'United States English,Midwestern United States English': 'United States English',
    'United States English,Midwestern,Low,Demure': 'United States English',
    'United States English,Midwestern,Minnesotan': 'United States English',
    'United States English,Minnesotan': 'United States English',
    'United States English,Mix of voices': 'United States English',
    'United States English,New York English': 'United States English',
    'United States English,New Yorker': 'United States English',
    'United States English,North Indiana': 'United States English',
    'United States English,Northeast US': 'United States English',
    'United States English,Northeastern,Rhode Island,Massachusetts': 'United States English',
    'United States English,Northern,Urban': 'United States English',
    'United States English,Okie': 'United States English',
    'United States English,Pacific North West United States': 'United States English',
    'United States English,Pacific Northwest ': 'United States English',
    'United States English,Pacific Northwest English': 'United States English',
    'United States English,Pittsburgh PA': 'United States English',
    'United States English,Russian': 'United States English',
    'United States English,Scandinavian': 'United States English',
    'United States English,Slight Dutch accent': 'United States English',
    'United States English,Slight lisp': 'United States English',
    'United States English,South Texas,Slightly effeminate,Conversational': 'United States English',
    'United States English,Southern African (South Africa, Zimbabwe, Namibia)': 'United States English',
    'United States English,Southern Appalachian English,Southern United States English': 'United States English',
    'United States English,Southwestern United States English': 'United States English',
    'United States English,Spoke Chinese when little,90% Pennsylvanian accent, 10% Chinese accent': 'United States English',
    'United States English,Texas': 'United States English',
    'United States English,Transatlantic English': 'United States English',
    'United States English,Unite States Midwest': 'United States English',
    'United States English,United States, west coast English ': 'United States English',
    'United States English,Upstate New York': 'United States English',
    'United States English,midwest': 'United States English',
    'United States English,new england/east coast': 'United States English',
    'United States English,plain,southern draw,west coast surfer dude': 'United States English',
    'United States English,southern United States,New Orleans dialect': 'United States English',
    'Vietnam': '',
    'Welsh English': 'Welsh English',
    'West African ': '',
    'West Indian': '',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad)': 'West Indies and Bermuda',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad),England English,Scottish English,United States English': 'West Indies and Bermuda',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad),Patois': 'West Indies and Bermuda',
    'england,london,academic': 'England English',
    'french accent': '',
    'french accent,French mid level accent': '',
    'french english': '',
    'mexican accent': '',
    'mix of american and british ,native polish': '',
    'nigeria english': '',
    'northen united states': '',
    'polish': '',
    'polish accent': '',
    'serbian': '',
    'serbian,United States English': 'United States English',
    'southern United States,United States English': 'United States English',
    'strong Latvian accent': '',
    'very slight Russian accent,Standard American English,Boston influence': '',
}


def normalize_accent_labels(dataset, label_column="accent", mapping=ACCENT_LABEL_MAP):
    """Apply ACCENT_LABEL_MAP to a HF dataset column.

    Values mapped to "" will be dropped by the existing filter_labeled()
    helper in wavlm_common.py, same as if they had never been labeled.
    """
    def _map(example):
        raw = example[label_column]
        example[label_column] = mapping.get(raw, raw) if raw is not None else raw
        return example
    return dataset.map(_map)