"""
Mapping from raw, inconsistent Common Voice 17 "accent" labels to a small set
of consistent accent classes for the WavLM accent-classification script.

- Labels that describe the same accent in different words (e.g. compound labels
  like "United States English,Midwestern" or aliases like "British accent") are
  collapsed onto one canonical label (e.g. "United States English", "England English").
- Labels that are one-off personal descriptions, ambiguous multi-accent combos with
  no clear primary accent, or accents with too few usable samples (no/almost no
  representation in the validation/test splits) are mapped to "" so that
  `filter_labeled()` in wavlm_common.py drops them automatically (it already treats
  "" the same as an unlabeled example).

"""

ACCENT_LABEL_MAP = {
    '2nd Language ': '',
    'A variety of Texan English with some German influence that has undergone the cot-caught merger': '',
    "A'lo": '',
    'Academic southern English,England English': 'British and Irish English',
    'Afrikaans English': '',
    'Australian English': 'Australian English',
    'Australian English,Canadian English': 'Australian English',
    'Australian English,Educated Australian Accent': 'Australian English',
    'Australian English,England English': 'Australian English',
    'Australian English,England English,Japanese': 'Australian English',
    'Australian English,General Australian': 'Australian English',
    'Australian English,Sydney - middle eastern seaboard Australian': 'Australian English',
    'Austrian': '',
    'Bangladeshi English': '',
    'Bangladeshi,Bangladesh English': '',
    'Born in West Germany in 1966, lived in Toronto, Ontario from 1985 to 2004, now in Central America.': '',
    'Brazilian': '',
    'Brazillian Accent': '',
    'British English / Received Pronunciation (RP)': 'British and Irish English',
    'British accent': 'British and Irish English',
    'Bulgarian': '',
    'California': 'North American English',
    'Canadian English': 'North American English',
    'Canadian English,Irish English': 'North American English',
    'Canadian English,Ontario': 'North American English',
    'Canadian English,SerpentX': 'North American English',
    'Canadian English,Swedish English': 'North American English',
    'Canadian English,United States English': 'North American English',
    'Canadian English,United States English,England English': 'North American English',
    'Caribbean Canadian ': 'North American English',
    'Chinese': '',
    'Czech accent': '',
    'Dutch': '',
    'Dutch English': '',
    'Dutch,European,Adjustable': '',
    'East African Khoja': '',
    'East Indian': '',
    'Eastern European English': '',
    'Eastern European,Romanian': '',
    'England English': 'British and Irish English',
    'England English,British': 'British and Irish English',
    'England English,Canadian English': 'North American English',
    'England English,East Anglian English': 'British and Irish English',
    'England English,Educated,non regional': 'British and Irish English',
    'England English,India and South Asia (India, Pakistan, Sri Lanka),Nepalese': 'India and South Asia',
    'England English,Lancashire, England ': 'British and Irish English',
    'England English,New Zealand English': 'Australian English',
    "England English,Porto des dels 3 anys aprenent anglès a l'escola i actualment m'estic preparant per a l'examen del B2.": '',
    'England English,Received English, tempered by 45 years living in the USA': 'North American English',
    'England English,Received Pronunciation': 'British and Irish English',
    'England English,Slightly lazy Midlands English ,Oxford English': 'British and Irish English',
    'England English,South London': 'British and Irish English',
    'England English,South London and Essex': 'British and Irish English',
    'England English,Southern England English with a subtle hint of Irish English.': 'British and Irish English',
    'England English,Swedish': 'British and Irish English',
    'England English,United States English': 'North American English',
    'England English,United States English,Brazilian Accent,EFL': 'North American English',
    'England English,United States English,English with Polish accent,Slavic English': 'North American English',
    'England English,Well spoken softly spoken Home Counties gay,softly spoken male,well spoken male,gay male': 'British and Irish English',
    'England English,Welsh English': 'British and Irish English',
    'England English,femalepublic school accent, quiet and under articualted finals': 'British and Irish English',
    'England English,south German / Swiss accent': '',
    'England English,southern UK,male': 'British and Irish English',
    'England English,southern english,sussex': 'British and Irish English',
    'England English,yorkshire': 'British and Irish English',
    'England West County': 'British and Irish English',
    'English north of England ': 'British and Irish English',
    'English with Swiss german accent': '',
    'European': '',
    'European English': '',
    'European English,French,Romanian': '',
    'European,German,Foreign,Non-native': '',
    'Filipino': 'Southeast Asian English',
    'Filipino,Canadian English': 'Southeast Asian English',
    'Filipino,United States English': 'Southeast Asian English',
    'French': '',
    'Generic European': '',
    'Georgian English': '',
    'German': '',
    'German Accent': '',
    'German English': '',
    'German English,England English': '',
    'German English,I am German and speak English as learned at school': '',
    'German English,Non native speaker': '',
    'Ghanaian english Accent,african regular reader': '',
    'Greek': '',
    'Hispanic': '',
    'Hong Kong English': 'Southeast Asian English',
    'Hong Kong English,Scottish English': 'Southeast Asian English',
    'Hungarian': '',
    'Hunglish': '',
    'India and South Asia (India, Pakistan, Sri Lanka)': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Basic': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Canadian English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),England English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),England English,United States English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Indian with a tinge of an RP accent': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),International Indian Accent': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),Singaporean English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),United States English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),United States English,England English': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),bangladesh': 'India and South Asia',
    'India and South Asia (India, Pakistan, Sri Lanka),try to maintain originality ': 'India and South Asia',
    'Indonesian': '',
    'International English,United States English,Australian English': 'Australian English',
    'Irish English': 'British and Irish English',
    'Irish English,Northern Irish English,belfast ': 'British and Irish English',
    'Israeli': '',
    'Israeli English': '',
    'Italian': '',
    'Japanese English': '',
    'Kazakhstan English': '',
    'Kenyan English': '',
    'Kenyan English accent': '',
    'Kiwi': 'Australian English',
    'Latin America,United States English': 'North American English',
    'Latin English': '',
    'Latino': '',
    'Latvian': '',
    'Liverpool English,Lancashire English,England English': 'British and Irish English',
    'Malaysian English': 'Southeast Asian English',
    'Malaysian English,England English': 'Southeast Asian English',
    'Malaysian English,Indonesian English': 'Southeast Asian English',
    'Malaysian English,Javanese,Indonesian English': 'Southeast Asian English',
    'Mid-Atlantic United States English,Philadelphia, Pennsylvania, United States English,United States English,Philadelphia Style United States English': 'North American English',
    'Mid-atlantic,England English,United States English': 'North American English',
    'Midatlantic': 'North American English',
    'Midwestern States (Michigan),United States English': 'North American English',
    'Midwestern US English (United States),United States English': 'North American English',
    'Mild Northern England English': 'British and Irish English',
    'Mix of american and british accent': '',
    'My accent is influenced by the phones of all letters within a sentence.,Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'Nepali': '',
    'New Zealand English': 'Australian English',
    'New Zealand English,Australian English,England English': 'Australian English',
    'New Zealand English,England English': 'Australian English',
    'New Zealand English,United States English': 'Australian English',
    'Nigerian ,West African ': '',
    'Nigerian English': '',
    'Non native speaker from France': '',
    'Non-native': '',
    'Non-native,German Accent': '',
    'North European English': '',
    'Northern England,England English': 'British and Irish English',
    'Northern Irish': 'British and Irish English',
    'Northern Irish,Norwegian,yorkshire': '',
    'Northern Irish,culchie': 'British and Irish English',
    'Northumbrian British English': 'British and Irish English',
    'Personal idiolect': '',
    'Polish English': '',
    'Rhode Island New England Accent': 'North American English',
    'Russian': '',
    'Russian English': '',
    'Russian,East Ukrainian ': '',
    'Scottish English': 'British and Irish English',
    'Scottish English,England English': 'British and Irish English',
    'Scottish English,Scottish English (West Coast),Scottish English (Ayrshire)': 'British and Irish English',
    'Singaporean English': 'Southeast Asian English',
    'Singaporean English,England English': 'Southeast Asian English',
    'Singaporean English,Malaysian English': 'Southeast Asian English',
    'Singaporean English,United States English': 'Southeast Asian English',
    'Slavic': '',
    'Slavic,East European,polish': '',
    'Slavic,Russian': '',
    'Slavic,polish': '',
    'Slovak': '',
    'South African  English accent ': 'Southern African',
    'South African English Accent ': 'Southern African',
    'South African accent ,Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'South Atlantic (Falkland Islands, Saint Helena)': '',
    'South Australia': 'Australian English',
    'South German accent,Alemannic German Accent,German,south-west German': '',
    'South Indian': '',
    'Southern African (South Africa, Zimbabwe, Namibia)': 'Southern African',
    'Southern African (South Africa, Zimbabwe, Namibia),England English': 'Southern African',
    'Southern Californian,United States English': 'North American English',
    'Spanish bilingual': '',
    'Spanish,Foreign,Non-native': '',
    'Swedish English': '',
    'Swedish accent': '',
    'Thai': '',
    'Transatlantic,Danish English': '',
    'Ukrainian': '',
    'United States English': 'North American English',
    'United States English combined with European English': 'North American English',
    'United States English,American Midwest': 'North American English',
    'United States English,American english with austrian accent': 'North American English',
    'United States English,Asian-American English': 'North American English',
    'United States English,Australian English': 'North American English',
    'United States English,Australian English,England English,Irish English': 'North American English',
    'United States English,Australian English,England English,New Zealand English,India and South Asia (India, Pakistan, Sri Lanka),international,Slovak': 'North American English',
    'United States English,British English': 'North American English',
    'United States English,California': 'North American English',
    'United States English,California English': 'North American English',
    'United States English,California English,Southern US English': 'North American English',
    'United States English,California,Valley': 'North American English',
    'United States English,Californian Accent': 'North American English',
    'United States English,Canadian English': 'North American English',
    'United States English,Canadian English,international': 'North American English',
    'United States English,Central American ': 'North American English',
    'United States English,Chicago ': 'North American English',
    'United States English,Cool': 'North American English',
    'United States English,England English': 'North American English',
    'United States English,England English,India and South Asia (India, Pakistan, Sri Lanka)': 'North American English',
    'United States English,English Second Language': 'North American English',
    'United States English,Foreigner English': 'North American English',
    'United States English,German Accent': 'North American English',
    'United States English,Hmong-American': 'North American English',
    'United States English,India and South Asia (India, Pakistan, Sri Lanka)': 'North American English',
    'United States English,Irish English': 'North American English',
    'United States English,Irish English,England English,Scottish English,Danish English': 'North American English',
    'United States English,Like a Kennedy ,Boston': 'North American English',
    'United States English,Mid-atlantic': 'North American English',
    'United States English,Mid-west United States English': 'North American English',
    'United States English,Midwest United States': 'North American English',
    'United States English,Midwestern': 'North American English',
    'United States English,Midwestern USA': 'North American English',
    'United States English,Midwestern United States English': 'North American English',
    'United States English,Midwestern,Low,Demure': 'North American English',
    'United States English,Midwestern,Minnesotan': 'North American English',
    'United States English,Minnesotan': 'North American English',
    'United States English,Mix of voices': 'North American English',
    'United States English,New York English': 'North American English',
    'United States English,New Yorker': 'North American English',
    'United States English,North Indiana': 'North American English',
    'United States English,Northeast US': 'North American English',
    'United States English,Northeastern,Rhode Island,Massachusetts': 'North American English',
    'United States English,Northern,Urban': 'North American English',
    'United States English,Okie': 'North American English',
    'United States English,Pacific North West United States': 'North American English',
    'United States English,Pacific Northwest ': 'North American English',
    'United States English,Pacific Northwest English': 'North American English',
    'United States English,Pittsburgh PA': 'North American English',
    'United States English,Russian': 'North American English',
    'United States English,Scandinavian': 'North American English',
    'United States English,Slight Dutch accent': 'North American English',
    'United States English,Slight lisp': 'North American English',
    'United States English,South Texas,Slightly effeminate,Conversational': 'North American English',
    'United States English,Southern African (South Africa, Zimbabwe, Namibia)': 'North American English',
    'United States English,Southern Appalachian English,Southern United States English': 'North American English',
    'United States English,Southwestern United States English': 'North American English',
    'United States English,Spoke Chinese when little,90% Pennsylvanian accent, 10% Chinese accent': 'North American English',
    'United States English,Texas': 'North American English',
    'United States English,Transatlantic English': 'North American English',
    'United States English,Unite States Midwest': 'North American English',
    'United States English,United States, west coast English ': 'North American English',
    'United States English,Upstate New York': 'North American English',
    'United States English,midwest': 'North American English',
    'United States English,new england/east coast': 'North American English',
    'United States English,plain,southern draw,west coast surfer dude': 'North American English',
    'United States English,southern United States,New Orleans dialect': 'North American English',
    'Vietnam': '',
    'Welsh English': 'British and Irish English',
    'West African ': '',
    'West Indian': '',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad)': '',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad),England English,Scottish English,United States English': '',
    'West Indies and Bermuda (Bahamas, Bermuda, Jamaica, Trinidad),Patois': '',
    'england,london,academic': 'British and Irish English',
    'french accent': '',
    'french accent,French mid level accent': '',
    'french english': '',
    'mexican accent': '',
    'mix of american and british ,native polish': '',
    'nigeria english': '',
    'northen united states': 'North American English',
    'polish': '',
    'polish accent': '',
    'serbian': '',
    'serbian,United States English': 'North American English',
    'southern United States,United States English': 'North American English',
    'strong Latvian accent': '',
    'very slight Russian accent,Standard American English,Boston influence': '',
}


def normalize_accent_labels(dataset, label_column="accent", mapping=ACCENT_LABEL_MAP):
    """Apply ACCENT_LABEL_MAP to a HF dataset column.

    Values mapped to "" will be dropped by the existing filter_labeled()
    helper in wavlm_common.py, same as if they had never been labeled.
    """
    def _map(example):
        raw = example[label_column]
        example[label_column] = mapping.get(raw, raw) if raw is not None else raw
        return example
    return dataset.map(_map)